dist: trusty
sudo: required
services:
- docker

language: go
go:
- "1.11.x"

env:
  - GO111MODULE=on
    GOFLAGS=-mod=vendor

install:
- make tools

script:
- make test
- make build
- make website-test
